### PR TITLE
Cmake oemsetting options

### PR DESCRIPTION
**Pull request by dwrobel**
It allows to specify the following settings:
    - binFileName,
    - keyHistoryFileName,
    - defaultRWDirName.

### CODE REVIEW

**Comment by dwrobel** [comment]
As it depends on PR https://github.com/WebPlatformForEmbedded/OCDM-Playready-Nexus-SVP/pull/1 so I added it here as well.

**Comment by pwielders** [comment]
@dwrobel currently all configuration is coming from the thunder condfigs, no specific config per plugin required. @svdmaar has aligned this with the IShell forwarding (Persistent path should be coming from here). 
@svdmaar can you check that this commit does not break it and otherwise explain @dwrobel how to get that informatin.
@bramoosterhuis can you check the CMake changes and probably you need this PR4. X stuff as well.

**Comment by dwrobel** [comment]
>@svdmaar has aligned this with the IShell forwarding (Persistent path should be coming from here).

Could you please explain where in the current code this functionality is already implemented?
In particular where those could be specified and and later on are assigned to the `oemSettings`:
```
        oemSettings.binFileName
        oemSettings.keyHistoryFileName
        oemSettings.defaultRWDirName
```

**Comment by svdmaar** [comment]
@dwrobel , please check this code: https://github.com/WebPlatformForEmbedded/OCDM-Playready/blob/master/MediaSystem.cpp#L490-L500

The idea is that IShell can tell you the paths you should be using. It's then up to you how to create subdirs.

**Comment by dwrobel** [comment]
> The idea is that IShell can tell you the paths you should be using. It's then up to you how to create subdirs.

Providing `subdirs` is not enough as you need to specify the `filename` as well. And I don't see that currently `IShell` provides any equivalents for things like `binFileName`, `keyHistoryFileName`, etc.

> no specific config per plugin required.

So you're proposing to add them _(any plugin specifics)_ to the `IShell` then?

Last not least that will bring back the `WPEFramework` dependency again?

**Comment by svdmaar** [comment]
@dwrobel : using IShell is it possible to derive the filename? For example is it always keyfile.z in a subdir of the persistent path? If not, then I think it needs to be passed in the JSON anyway.

@pwielders : what is your input?

**Comment by dwrobel** [comment]
I rebased that on the current master, and IMHO nothing prevents you from overwriting any settings based on the `IShell` on top of this change _(as no one is forced to specify anything on the `cmake` level)_.

**Comment by pwielders** [comment]
Our system is designed to be generic. All config goes into 1 location (not distributed all through the system and not being redundant). This means that for example, the location of persistent storage and readonly storage is a configuration set once in the "main" config, found at the toplevel config file.
For this we forwarded the IShell interface, so you can get the PeristentPath() or DataPath() (Read Only Memory) for the files that you need to write or read. Theis means that if this OCDM is deplyed on a Box A, where the persistent storage is in /hdd/secure/store, behaves the same as on box B, where the persistent storage is in /flash/store. Without changing the names in the OCDM config of this DRM.
So if you need to write data, make sure you use the IShell->PersistentPath() as a prefix to the files.

**Comment by bramoosterhuis** [comment]
Closing this PR because we now use a new interface and all code is verified on PlayReady 4 and 3

**Pull request closed without merging**
