### PR TITLE
WPE-257: Pass customData further down + call callbacks on errors too.

### PR DESCRIPTION
**Pull request by pawel-stanek-ml**

### CODE REVIEW

**Comment by pawel-stanek-ml** [comment]
I haven't compile tested it yet.

**Comment by dwrobel** [comment]
On top of it https://github.com/WebPlatformForEmbedded/OCDM-Playready-Nexus-SVP/pull/3 fixes compilation issues with the recent changes made to cdmi.h

**Comment by dwrobel** [comment]
Rebased commit can be found here: https://github.com/dwrobel/OCDM-Playready-Nexus-SVP/commit/c2c490fd79236fcdd1ef11a6a2ad72d65cb86a95

**Comment by svdmaar** [comment]
Loved it back then: https://github.com/WebPlatformForEmbedded/OCDM-Playready/commit/3a795f22141e0ef5c06b104d26474ef784df8843 . :-) Still do. So: looks good to me.

**Pull request merged**
